### ISSUE TITLE
Missing data from Statcast

### ISSUE THREAD

**Issue by vfigueroa** [jldbc/pybaseball#272] opened 2022-05-27 12:30 UTC
I have noticed that when I run `data = statcast()` to get yesterdays pitching data it returns an empty data frame attached are some pictures showing the last day I was able to get data(May 22nd). I am using a python notebook in VSCode and have restarted my kernel as well as removing my cache to try to troubleshoot this issue.

<img width="535" alt="Screen Shot 2022-05-25 at 6 10 30 PM" src="https://user-images.githubusercontent.com/32070827/170699461-ae851636-1e2c-45cf-aa3b-6c135165ac5a.png">

<img width="563" alt="Screen Shot 2022-05-25 at 6 11 00 PM" src="https://user-images.githubusercontent.com/32070827/170699481-c3509db9-d906-4db9-a34c-0dc2d2393725.png">

**Comment by tjburch** [comment] 2022-07-27 02:03
Have you found a resolution to this? I'm able to pull data from that time range. 

This reads like it might have been a cache problem, maybe consider clearing that and trying again?

**Comment by ksullivan1031** [comment] 2022-08-11 18:25
I think I am seeing something similar when pulling statcast data for Aug 5,8,9.  For some reason only these days are affected

<img width="753" alt="Screen Shot 2022-08-11 at 1 25 34 PM" src="https://user-images.githubusercontent.com/16626873/184212104-5bffc637-07c8-491e-b88b-cce50ca4f887.png">

Can someone explain the proper way to clear the cache?

Thanks

**Comment by tjburch** [comment] 2022-08-11 18:31
@ksullivan1031 - there should be a folder in your user directory: `~/.pybaseball/cache`. Easiest way is to just clear that directory entirely (or you could try to search for the offending cached query and try to delete just it).

For more info about the cache see [the docs](https://github.com/jldbc/pybaseball/blob/master/docs/caching.md). Those are reasonable queries so maybe for your use case you might consider just disabling it.

**Comment by tjburch** [comment] 2022-10-01 01:37
Were you able to resolve? Closing if so.

**Comment by tjburch** [comment] 2022-12-03 20:21
Closing due to inactivity and inability to reproduce

**Closed by tjburch** 2022-12-03 20:21 UTC
