### ISSUE TITLE
Can't seem to get pitching/batting stats.

### ISSUE THREAD

**Issue by shortenedname** [jldbc/pybaseball#381] opened 2023-08-22 17:15 UTC
I was following a tutorial grabbing batting and pitching stats and my Pandas Dataframe was only returning an Empty Dataframe with the only column being "IDfg". I then went to the repo and copy pasted the batting_stats() and pitching_stats() code examples and am still getting the same thing. Statcast function works for me though, would like to see if I'm doing something wrong 

`` 
![pybaseball](https://github.com/jldbc/pybaseball/assets/33242494/6075cfdf-d652-4abd-92bd-4ba6626b1fba)

**Comment by shortenedname** [comment] 2023-08-22 17:40
Wanted to come back and add/report that importing and using batting_stats_range() and pitching_stats_range() functions seems to work, so I'm assuming it's got something to do w/ fangraphs changing some stuff like another person pointed out in a different issue and the updates need to be reflected.

**Comment by ss77995ss** [comment] 2023-08-23 02:47
I think it is the same issue with #376 
The fix PR is merged to the main branch but not release to `PyPI`.

Therefore, if you want to have the fix version you might try to uninstall `pybaseball` and install the main branch's code.

```diff
- pip install pybaseball
+ pip install git+https://github.com/jldbc/pybaseball.git@master
```

**Comment by stephenlacey531** [comment] 2023-08-23 11:44
Works for me thx !

**Comment by ss77995ss** [comment] 2023-08-23 14:39
Hi @shortenedname 
Have you tried to uninstall `pybaseball` first?
If you not uninstall the old version. It may still use the old code.
I forgot to add the uninstall line in my previous comment. 😞 

```
pip uninstall pybaseball
pip install git+https://github.com/jldbc/pybaseball.git@master
```

**Comment by tcamino24** [comment] 2023-08-23 15:08
Hey @ss77995ss 
currently having these same issues in JupyterLab environment. The kernel will not finish when i try and run pip uninstall pybaseball or when i try and call on the newly imported package provided above in this thread

**Comment by tcamino24** [comment] 2023-08-23 15:23
@ss77995ss where should i be running that code? in jupyterlabs it just creates an infinite loop and in my command prompt it says pip is not recognized

**Comment by stephenlacey531** [comment] 2023-08-23 15:24
Also, you might need to restart your notebook / kernel following the install of %pip install git+https://github.com/jldbc/pybaseball.git@master

**Comment by shortenedname** [comment] 2023-08-23 15:42
@stephenlacey531 @ss77995ss thank you both for being lovely and helping me out. I got in the terminal of jupyterlabs and uninstalled, then ran the `%pip install git+https://github.com/jldbc/pybaseball.git@master` in an actual notebook in Jupyter and not my add-on in VSCode, restarted the kernel and it worked on both Jupyter and in VSCode. 👍

**Comment by shortenedname** [comment] 2023-08-23 15:43
@stephenlacey531 @ss77995ss thank you both for being lovely and helping me out. I got in the terminal of jupyterlabs and uninstalled, then ran the `%pip install git+https://github.com/jldbc/pybaseball.git@master` in an actual notebook in Jupyter and not my add-on in VSCode, restarted the kernel and it worked on both Jupyter and in VSCode. 👍 

I kind of want to close the issue, but I'll wait for @tcamino24 to read my update and see if what I did works for them

**Comment by ss77995ss** [comment] 2023-08-23 15:44
@tcamino24
try `!pip uninstall -y pybaseball`. This command will bypass the confirmation and the infinite loop should disappear

**Comment by tcamino24** [comment] 2023-08-23 15:47
that worked for the uninstall thank you! when im going to call on the package in jupyterlabs, what should i try and import now? LIke before it was import pybaseball and then from pybaseball import batting_stats. What should replace pybaseball now in the code, something like `git+https://github.com/jldbc/pybaseball.git@master` ?

**Comment by ss77995ss** [comment] 2023-08-23 15:48
@shortenedname I'm glad to help!
It is weird we can type to confirm in Colab but not in VScode's jupyter notebook

@tcamino24 you can still import pybaseball after installing git+https://github.com/jldbc/pybaseball.git@master
Have a try!

**Comment by tcamino24** [comment] 2023-08-23 15:52
worked flawlessly! thanks so much for the help, thought the FanGraphs update was gonna completely derail the rest of the season. I really appreciate it, take care!

**Closed** 2023-08-23 15:55 UTC

**Comment by bclark08** [comment] 2023-09-08 04:13
I am still getting the blank IDfg table.  I did the full uninstall and reinstalled using git.  I then checked /pybaseball/datasources/fangraphs.py and confirmed that line 14 reads:

`_FG_LEADERS_URL = "/leaders-legacy.aspx"`

I've restarted the jupyter notebook from which I do my weekly stats and am still getting the blank table.  Anyone experiencing this or know how to fix?

**Comment by ss77995ss** [comment] 2023-09-08 04:49
Hi @bclark08 could you maybe provide some of your code?
I'll try to reproduce the issue and find what cause the problem

**Comment by bclark08** [comment] 2023-09-08 20:45
@ss77995ss thank you for responding!

I am at work right now and don't have access to my code, but I will try to remember to give you a code snippet later tonight.  I think it is actually an issue with Jupyter Notebook, as I have had similar issues with other packages in the past.

On the upside, I was rather frustrated and merged all of my code into a single, locally-saved script and ran it from the command line.  This worked flawlessly, which further heightens my suspicion that there is an issue with Jupyter Notebook--I am guessing having something to do with where or how I initially installed and saved it.

**Comment by ss77995ss** [comment] 2023-09-09 01:11
@bclark08 No hurry!

Could you open another issue once you get your code? Since this one is closed. We could discuss in the newest issue.
