### ISSUE TITLE
batting_stats_range breaks when parsing through the date '2021-06-25'

### ISSUE THREAD

**Issue by dk-sa1** [jldbc/pybaseball#218] opened 2021-06-28 00:32 UTC
When using the batting_stats_range function, there is an issue when parsing through 6/25/2021. 

When it breaks, you receive corrupt data. One such piece being the player José Abreu appearing as "JosÃ© Abreu". As well as only receiving a couple rows of data ( As opposed to several hundred for a typical day of data). 

Below are some code blocks that work and do not work. 

Works:
data = batting_stats_range("2021-06-25", "2021-06-27")
data = batting_stats_range("2021-06-25", "2021-06-25")

Does NOT Work:
data = batting_stats_range("2021-06-24", "2021-06-27")
data = batting_stats_range("2021-06-24", "2021-06-25")

For some reason, you can start on 6/25 with no issues. But you cannot parse over, nor end on 6/25 without receiving corrupt data.

**Comment by dk-sa1** [comment] 2021-06-28 00:43
The issue arises for the same date in 2019.

**Comment by jmcous** [comment] 2021-06-30 01:36
I'm having other problems with batting_stats_range, I don't know if this is related but:
`from IPython.display import display

a=batting_stats_range('2021-05-25','2021-06-23')
b=pitching_stats_range('2021-05-25','2021-06-23')
print(a.shape)
print(b.shape)

display(a)
display(b)`

The batting stats range query only returns 21 rows, just players that start with 'A'.
![image](https://user-images.githubusercontent.com/29820512/123888688-ac1e2a80-d919-11eb-99b5-9bdf4ae4b2bc.png)

**Comment by bdilday** [comment] 2021-07-17 12:32
it looks like in the cases that the data gets truncated, beautiful soup can't use utf-8 so falls back on a different encoding, e.g., 

```
>>> from pybaseball.league_batting_stats import batting_stats_range, get_soup
>>> start_dt = end_dt = "2021-05-01"
>>> data = batting_stats_range(start_dt, end_dt)
>>> len(data)
334
>>> soup = get_soup(start_dt, end_dt)
>>> soup.original_encoding
'utf-8'
>>> 
>>> start_dt = end_dt = "2021-05-02"
>>> data = batting_stats_range(start_dt, end_dt)
>>> len(data)
10
>>> soup = get_soup(start_dt, end_dt)
>>> soup.original_encoding
'Windows-1252'
>>> 
```

this seems to happen when the page header or footer includes a link to https://fbref.com/es or https://fbref.de, because they include the characters ú and ß (in Fútbol and Fußball). so long story short this looks like inconsistent encoding between the header / footer and the main part of the page 

because it doesnt depend on the data, the date where it happens isn't reproducible either

Closed by https://github.com/jldbc/pybaseball/pull/223

**Closed** 2021-07-18 10:41 UTC
Labels: bug
