### ISSUE TITLE
Baseball Savant Scraping Issue

### ISSUE THREAD

**Issue by rensmacneill** [jldbc/pybaseball#20] opened 2018-04-03 12:45 UTC
Hi there, 

I first want to say thank you for your awesome work in putting together pybaseball. I was playing around with the package yesterday and ran the fivethirtyeight New Science of Hitting example with no issues. Today I was running some statcast and statcast_batter queries in much the same way as in the example, however I run into errors every time.

I now receive the following error when attempting to print the shape of the initial dataset in the New Science of hitting example: ValueError: could not convert string to float: 'Sinker'.

When running statcast_batter with an end-date as in the example I receive an Error: Query Timeout message. However when statcast_batter is run without an end-date, it returns without an error, however the player_id is ignored in the returned data set. 

I have attached an image to better illustrate what I'm experiencing (run here with David Ortiz's player_id as in the statcast_batter example).
![screen shot 2018-04-03 at 10 39 26 pm](https://user-images.githubusercontent.com/7392763/38249829-5a9679d4-3790-11e8-8c49-4d7905e34121.png)

I have run this using both Python 2.7.10 and Python 3.6.1, with the same behaviour for both.

EDIT: I have tried manually scraping the data using the technique set out by @alanrkessler and baseball savant is returning a 'Error: Query Timeout. Please try to limit your query to less data.' as the singular field of the csv when you attempt to scrape the data.

**Comment by jldbc** [comment] 2018-04-04 01:47
Thanks for flagging, I'll look into this. In the other `statcast` function this timeout issue is caused by requesting more than a certain number of rows, which could be fixed by breaking it into multiple requests and iterating. I could see Ortiz hitting the max row count given his career length. 

The 'Sinker' ValueError sounds like a column may have changed.

**Comment by rensmacneill** [comment] 2018-04-04 01:55
According to Darren Willman and Bill Petti on twitter (see [https://twitter.com/BillPetti/status/981155132585988096](url) ) there are some additional fields in each baseballsavant query result now, which would explain why the ValueError is appearing.

I'll mess around with iterating through larger requests tonight. Could the extra fields be causing the player_id to be ignored in a one-day query?

Thanks for your response also @alanrkessler, I'll let you know how things go.

**Comment by jldbc** [comment] 2018-04-04 02:09
**For statcast_batter (and by extension probably statcast_pitcher)**
Let me know how that's going, I haven't gotten to the bottom of that one yet. It looks like they started enforcing stricter limits on query size for these. `statcast_batter('2008-04-01','2008-04-10', 120074)`  works and returns ~36k rows but  `statcast_batter('2008-04-01','2008-04-10', 120074)` onward returns exactly 40,000 rows and then eventually times out if you extend it too far. The solution is probably breaking it into several smaller requests if the date range is larger than N days. 

**For statcast**
The 'pitch_name' column was breaking `statcast` which I just merged a fix for. Maybe the lesson here is to be explicit about which columns to accept so things don't break the next time this happens.

**Comment by jldbc** [comment] 2018-04-04 02:11
Oops, meant to say `statcast_batter('2008-04-01','2008-04-11', 120074)` for the second query example that returns 40k.

**Comment by rensmacneill** [comment] 2018-04-08 13:47
Just to give you a quick update (or lack thereof). Unfortunately I've been too busy to properly test a solution to `statcast_batter` just yet. Also, thanks for merging your fix for `statcast`, everything works well on that front now.

**Comment by rensmacneill** [comment] 2018-04-11 00:39
Regarding `statcast_batter`, when you run `statcast_batter('2008-04-01','2008-04-10', 120074)`, have you found that the `player_id` is ignored? When I print the output from that query, I receive the data seen in the attached screenshot.
<img width="494" alt="screen shot 2018-04-11 at 10 38 10 am" src="https://user-images.githubusercontent.com/7392763/38590453-9af03af8-3d74-11e8-82a4-6706effe239a.png">

**Comment by andersonfrailey** [comment] 2018-04-18 21:10
For `statcast_pitcher` and `statcast_batter`, would it be possible to break up large requests into multiple queries? I've found that I can run requests for about two months worth of games without issue, but anymore than that I run into timeout problems.

I haven't worked too much with requests, but I'd be happy to help with this where I can.

Also, I had the same issue as @rensmacneill in that when I run `statcast_batter` in that `player_id` seems to be ignored.

**Comment by jldbc** [comment] 2018-04-23 04:26
Baseball Savant changed their url structure for statcast search like @dingerz is saying. In place of player_lookup, the hitting side is now using batters_lookup and the pitching side is using pitchers_lookup.

I'll try to send a change out on the repo tonight and push to pypi tomorrow. 

@andersonfrailey: want to open a separate thread for crawling through longer date ranges on these? It's worth implementing but better off tracked as its own issue.

**Comment by andersonfrailey** [comment] 2018-04-23 12:32
@jldbc, yep. I'll do it a little later this week/this up coming weekend when I have time to sit down and think it through some more.

**Closed** 2018-05-27 21:05 UTC
