### ISSUE TITLE
Cache Generates Massive Amounts of Empty Files

### ISSUE THREAD

**Issue by BOBONA** [jldbc/pybaseball#437] opened 2024-07-04 03:59 UTC
Using the cache is generating these files. 

_small_request1720064495.401325.cache_record.json

The files contain `{"func": "_small_request", "args": [`

**Comment by bdilday** [comment] 2024-07-04 20:18
Thanks for raising this! I have been wondering why `cache.purge()` fails to work for me and I think this is the cause. I think the root cause is the cache is trying and failing to serialize dates. I think it is fixed by https://github.com/jldbc/pybaseball/pull/438

**Closed** 2024-07-12 15:07 UTC
