### ISSUE TITLE
Question - Statcast pitcher spin rate

### ISSUE THREAD

**Issue by joshhejka** [jldbc/pybaseball#58] opened 2019-06-23 15:26 UTC
When using statcast_pitcher, there is a column "spin_rate_deprecated". There is also "spin_dir", "break_angle_deprecated", and "break_length_deprecated", all of which appear to be "NaN" for 2019 stats at the very least. Is there any way to access spin rate/spin direction/etc. for 2019 since these columns are now deprecated?

**Comment by tpoatsy3** [comment] 2019-08-21 18:40
In short, no, there is no way to access the old data. In fact, I can't even get the data from 2018 or earlier. However, I did find a paper from Professor Nathan from the University of Illinois on how to calculate the spin axis from other statcast data. I'm going to add a function that calculates the spin axis and magnitude to compensate for their deprecation. Could you post whatever old data you might have so that I can be sure that the values I end up with are similar to what you might have (orientation and units are my biggest concerns).

**Comment by jldbc** [comment] 2019-08-25 18:04
The oldest data I have (in terms of time collected) is from Dec 2017, and these were all null by that point in time. I think your best bets here are either to find an old pitchfx csv in someone else's repo, or to see if Prof Nathan has any reproducible examples you can use to verify that your approach is working

**Comment by tpoatsy3** [comment] 2019-08-30 18:40
Thanks! In the meantime, I created a `statcast_pitcher_spin` function that shows the user how much break on each pitch is due to spin and two angles of the spin axis. These seemed to be the most interested calculations. They're all defined in the documentation I wrote up for the function. I'm creating a pull request for my contribution now.

**Comment by schorrm** [comment] 2021-03-09 09:45
Closed by #64

**Closed by schorrm** 2021-03-09 09:45 UTC
Labels: enhancement, in progress
